Remove inline Javascript for administrator/components/com_newsfeeds/field/modal/newsfeedsfield
joomla-projects/joomla-es6 pull request #84
Opened 2018-02-27 19:32 UTC by astridx

Pull Request for Issue # .

### Summary of Changes
Remove Inline JavaScript of administrator/components/com_newsfeeds/field/modal/newsfeedsfield

### Testing Instructions
You can test in com_menu. You can create a menu item with a single newsfeed and select a newsfeed.

2018-02-27 19:43 UTC, C-Lodder commented on administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
> +		$doc = \JFactory::getDocument();
`\JFactory` >> `Factory`

2018-02-27 19:43 UTC, C-Lodder commented on administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
> +				$doc->addScriptOptions('newsfeed_id', $this->id);
and replace `$doc->` with `Factory::getDocument()->`

2018-02-28 08:10 UTC, dneukirchen commented
pr for #55

2018-03-07 15:25 UTC, C-Lodder commented
@astridx would you midn fixing he conflicts please?

2018-03-08 09:46 UTC, astridx commented
This three files are not changed in this PR. They came in by mistake. Is there an easy way to exclude these files?

2018-03-08 10:33 UTC, C-Lodder commented
I'm not sure how to revert a single file in Git, but I suppose you can just copy and paste the code from the file in the repo, then commit that.

2018-03-08 14:17 UTC, astridx commented
Conflicts solved.

2018-03-11 16:14 UTC, dneukirchen requested changes
Please revert changes to media action plugins

2018-03-11 21:48 UTC, astridx commented
See: https://github.com/joomla-projects/joomla-es6/pull/106

2018-03-11 21:48 UTC, closed without merging