Transform com_finder to ES6 and remove inline script  [ Part1 ]
joomla-projects/joomla-es6 pull request #90
Opened 2018-03-01 20:59 UTC by Anu1601CS

Pull Request for Issue 
1.   #8 
2.  #55

2018-03-01 21:00 UTC, Anu1601CS commented
We can't make dog happy  :(

2018-03-07 15:24 UTC, C-Lodder approved these changes

2018-03-07 15:24 UTC, C-Lodder commented
@Anu1601CS dont worry about the `no-alert` warnings

2018-03-09 07:56 UTC, dneukirchen requested changes
Rest looks fine. Thank you.

2018-03-09 07:57 UTC, dneukirchen commented on media/com_finder/js/filters.es6.js
> +        if (window.confirm(Joomla.JText._('COM_FINDER_INDEX_CONFIRM_DELETE_PROMPT'))) {
We can simplify this and remove 1 if and the else clause.

```
if (pressbutton === 'filters.delete' && !window.confirm(Joomla.JText._('COM_FINDER_INDEX_CONFIRM_DELETE_PROMPT'))) {
    return false 
}
...
```

2018-03-10 16:11 UTC, dneukirchen approved these changes

2018-03-10 16:12 UTC, merged