Transform com_finder to ES6 and remove inline script [ Part 2 ]
joomla-projects/joomla-es6 pull request #91
Opened 2018-03-01 21:02 UTC by Anu1601CS

Pull Request for Issue 
1.  #8 
2.  #55

2018-03-07 15:23 UTC, C-Lodder approved these changes

2018-03-11 16:15 UTC, dneukirchen requested changes

2018-03-11 16:15 UTC, dneukirchen commented on media/com_finder/js/maps.es6.js
> +      return true;
Same as in https://github.com/joomla-projects/joomla-es6/pull/90#pullrequestreview-102567078

2018-03-11 16:15 UTC, dneukirchen commented on media/com_finder/js/maps.es6.js
> +        if (window.confirm(Joomla.JText._('COM_FINDER_MAPS_CONFIRM_DELETE_PROMPT'))) {
please add a todo

2018-03-11 17:39 UTC, Anu1601CS commented
@dneukirchen done!

2018-03-11 17:47 UTC, dneukirchen approved these changes

2018-03-11 17:47 UTC, merged

2018-03-11 17:47 UTC, dneukirchen commented
thx @Anu1601CS